### PR TITLE
chore: bump npm deps

### PR DESCRIPTION
**Pull request by aduh95**
Apply all minor and patch updates available for the semvere-ranges we are targeting.

### CODE REVIEW

**Comment by aduh95** [comment]
The only reason was I think we want to release a new version soon, and I figure having all deps up-to-date was a good idea. I'm fine with skipping.

**Comment by aduh95** [comment]
Nice, does that mean we are to release a new version today?

**Comment by arcanis** [comment]
I think so, although we don't have a publish workflow yet so it won't be possible to publish to npm 🤔

**Comment by aduh95** [comment]
Micheal set up a `NPM_TOKEN` secret that can let us do that from GitHub Actions. I think we just need to do it, if we can re-use a workflow from somewhere else, that should be pretty straight forward. What were you using before?

**Comment by aduh95** [comment]
Some other nodejs repos are using https://github.com/nodejs/node-core-utils/blob/main/.github/workflows/release-please.yml, which requires the commit messages to follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) convention.

**Pull request merged**
