### PR TITLE
fix: add `npm view` to transparent commands

### PR DESCRIPTION
**Pull request by styfle**
- Related to https://github.com/nodejs/corepack/issues/157

### CODE REVIEW

**Review by aduh95 — APPROVED** [review]
Docs: https://docs.npmjs.com/cli/v8/commands/npm-view

**Comment by ljharb** [comment]
it kind of seems like it'd be a more usable default to assume everything is transparent, and explicitly exclude the *opaque* ones.

**Comment by arcanis** [comment]
> it kind of seems like it'd be a more usable default to assume everything is transparent, and explicitly exclude the _opaque_ ones.

Allowing new commands isn't a major change, whereas forbidding some is.

Generally I'm not sure how I feel about this change. While on surface it makes some sense, in practice it bypasses any registry configuration configured for the project (which can lead to potential security problems if the information you get is obtained from the public one instead of the private one). To avoid that one should call `yarn npm info` instead, which leverages the Yarn configuration.

There's an argument that this won't matter in most cases, but there's also the opposite argument: the cases where this matter are more likely to make this easy mistake unless the system prevents them to do so.

**Comment by ljharb** [comment]
> Allowing new commands isn't a major change, whereas forbidding some is.

that is a very good point. another alternative is disallowing *all* commands unless they're explicitly marked as opaque or transparent - then it'd always be semver-minor to mark a new command.

**Comment by aduh95** [comment]
@styfle What do you think of https://github.com/nodejs/corepack/pull/158#issuecomment-1215600771? Going back to my idea of providing an ENV variable to disable the usage error would let user/CLI tools that know what they're doing bypass the Corepack check while avoiding to introduce errors for the most common case. (So you would do something like `COREPACK_IGNORE_PACKAGE_JSON=1 npm view …` or `COREPACK_IGNORE_PACKAGE_JSON=1 npm install -g …`)

**Comment by arcanis** [comment]
Fwiw I agree an environment variable would be reasonable.

Bikeshedding the name, I'd suggest `COREPACK_ENABLE_STRICT_CHECK`, which would default to `1`; it would match other similar settings, avoid the double negation, and is less ambiguous than just referencing the package.json.

**Comment by styfle** [comment]
How about `COREPACK_ENABLE_STRICT=1` to enable the error and `COREPACK_ENABLE_STRICT=0` to disable it?

**Comment by aduh95** [comment]
@styfle  do you still want this merged now that https://github.com/nodejs/corepack/pull/167 has landed?

**Comment by styfle** [comment]
> While on surface it makes some sense, in practice it bypasses any registry configuration configured for the project

Given this, I think we should close and rely on the new `COREPACK_ENABLE_STRICT=0` env var.

I'm also curious if we can make `-g` or `--global` transparent by default but perhaps I'm overlooking something in those cases too.

**Pull request closed without merging**
