### PR TITLE
feat!: remove `--all` flag

### PR DESCRIPTION
**Pull request by aduh95**
Force users to opt-in into the package managers they want to support. As more and more package managers are added to Corepack, it's more and more unlikely that our users will be interested in _all_ the package managers Corepack supports, and it is unreasonable to expect Corepack maintainers would be able to perform security audits.

### CODE REVIEW

**Review by arcanis — CHANGES_REQUESTED** [review]
I find the increased friction in user experience a little problematic. Running `corepack enable` and things Just Work is easy. having to run the command multiple times isn't, especially if the only message people get is "command not found". Can we find alternatives?

**Comment by aduh95** [comment]
Yes unfortunately it is likely some script out there relies on it. We could deprecate `corepack enable`, freeze it to always mean `corepack enable pnpm@latest yarn@1.x` (i.e don't add more package manager to it), and possibly make it emit a warning.

I expect the `--all` flag is good to go, no?

**Comment by arcanis** [comment]
> I expect the --all flag is good to go, no?

The `--all` flag was intended to help build base offline base images for cloud providers, which frequently want all tools to be included in their images. I don't have a strong opinion as to whether this is super useful or not, but I'd tend to refrain from removing it, to avoid unneeded friction.

**Comment by aduh95** [comment]
Maybe @styfle would have an opinion there? I would expect Cloud provider to be "picky" about which package managers they enable by default, as more and more package managers are added to Corepack, I would expect they want to activate only a subset.

**Comment by styfle** [comment]
> I would expect they want to activate only a subset.

At Vercel, we only enable the package manager found in package.json.

I didn't know the `--all` flag existed until now.

I think we need to look at more long term and see how this would impact the scenario when `corepack enable` is no longer needed, presumably when it goes stable https://github.com/nodejs/corepack/issues/104

**Review by arcanis — APPROVED** [review]
Not 100% convinced, but I don't have a very strong opinion either way - it can be added back later on if really needed.

**Comment by nickmccurdy** [comment]
How do we run upgrade package managers like we could before this change?

`corepack prepare --activate pnpm` works, but `corepack prepare --activate yarn` errors with:

```
Internal Error: Error when performing the request to https://registry.npmjs.org/yarn; for troubleshooting help, see https://github.com/nodejs/corepack#troubleshooting
    at fetch (/usr/local/Cellar/corepack/0.25.2/libexec/lib/node_modules/corepack/dist/lib/corepack.cjs:22882:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchAsJson (/usr/local/Cellar/corepack/0.25.2/libexec/lib/node_modules/corepack/dist/lib/corepack.cjs:22896:20)
    at async fetchAvailableVersions (/usr/local/Cellar/corepack/0.25.2/libexec/lib/node_modules/corepack/dist/lib/corepack.cjs:22960:20)
    at async fetchAvailableVersions2 (/usr/local/Cellar/corepack/0.25.2/libexec/lib/node_modules/corepack/dist/lib/corepack.cjs:22999:14)
    at async /usr/local/Cellar/corepack/0.25.2/libexec/lib/node_modules/corepack/dist/lib/corepack.cjs:23428:25
    at async Promise.all (index 0)
    at async Engine.resolveDescriptor (/usr/local/Cellar/corepack/0.25.2/libexec/lib/node_modules/corepack/dist/lib/corepack.cjs:23425:22)
    at async PrepareCommand.execute (/usr/local/Cellar/corepack/0.25.2/libexec/lib/node_modules/corepack/dist/lib/corepack.cjs:24135:24)
    at async PrepareCommand.validateAndExecute (/usr/local/Cellar/corepack/0.25.2/libexec/lib/node_modules/corepack/dist/lib/corepack.cjs:21173:22)
```

**Comment by nickmccurdy** [comment]
The old `--all` functionality that updates pnpm and Yarn can be replicated with:
```
corepack prepare --activate pnpm yarn
```

**Comment by zanminkian** [comment]
> The old `--all` functionality that updates pnpm and Yarn can be replicated with:
> 
> ```
> corepack prepare --activate pnpm yarn
> ```

Why not using `corepack install -g pnpm && corepack install -g yarn`? `prepare` subcommand is confused and is not listed in `corepack -h`.

**Pull request merged**
