### PR TITLE
chore: update dev dependency proxy-agent to 6.2.2

### PR DESCRIPTION
**Pull request by Trott**
This is to update the indirect vm2 dependency and resolve some dependabot alerts.

### CODE REVIEW

**Review by arcanis — APPROVED** [review]

**Comment by merceyz** [comment]
This PR doesn't change the vm2 version, it's locked here https://github.com/nodejs/corepack/blob/6090fe7cbea7cebb1c6fee93d1ff417cb01da928/package.json#L99.

**Comment by arcanis** [comment]
Ah right, we completely disabled vm2 to avoid this kind of problem. Still, the warnings from automation will be annoying.

I wonder if we could avoid it by using a link/portal rather than a patch, to completely prevent vm2 from being in the lockfile? 🤔

**Comment by Trott** [comment]
Going to go ahead and land as it updates a few things and is hopefully harmless (and might quiet the automation). Feel free to revert or force push out if I'm messing anything up by doing that....

**Comment by Trott** [comment]
Ugh, it didn't resolve a single warning... :-(

**Pull request merged**
