### PR TITLE
fix: add `npm bin` to transparent commands

### PR DESCRIPTION
**Pull request by styfle**
- Related to https://github.com/nodejs/corepack/issues/157

### CODE REVIEW

**Comment by aduh95** [comment]
Sorry for my ignorance, what's the use-case for using `npm bin` in a non-npm package?

Docs: https://docs.npmjs.com/cli/v8/commands/npm-bin

**Comment by arcanis** [comment]
I agree, I don't see how `npm bin` is relevant to non-npm projects (except maybe when the `-g` flag is set, but this PR doesn't check that).

**Comment by styfle** [comment]
> what's the use-case for using npm bin in a non-npm package?

Its useful to append to the `PATH` so that you can run scripts like `tsc` instead of `./node_modules/.bin/tsc`.

https://github.com/vercel/vercel/blob/e34858d0828d97a7ccdedc36ff739cd051e20101/packages/next/src/index.ts#L429-L430

**Comment by ljharb** [comment]
Note that npm 9 is removing `npm bin`

**Comment by styfle** [comment]
@ljharb Where do you see that? Is there a roadmap I missed?

**Comment by ljharb** [comment]
@styfle https://github.com/npm/statusboard/issues/537

**Comment by merceyz** [comment]
> > what's the use-case for using npm bin in a non-npm package?
> 
> Its useful to append to the `PATH` so that you can run scripts like `tsc` instead of `./node_modules/.bin/tsc`.
> 
> https://github.com/vercel/vercel/blob/e34858d0828d97a7ccdedc36ff739cd051e20101/packages/next/src/index.ts#L429-L430

That's assuming the package manager used by the project implements the same behaviour as `npm` which isn't guaranteed.

**Comment by ljharb** [comment]
It's also worth noting that that use case is wildly insecure and dangerous, because of the potential for a package to silently shadow a system command.

**Pull request closed without merging**
